inherit_from: .rubocop_todo.yml

require: rubocop-rspec

inherit_mode:
  merge:
    - Exclude

AllCops:
  SuggestExtensions: false
  UseCache: true
  CacheRootDirectory: tmp/rubocop_cache_rails_dir
  MaxFilesInCache: 4000
  NewCops: enable
  Exclude:
    - db/schema.rb
    - features/step_definitions/web_steps.rb
    - features/support/selectors.rb
    - lib/tasks/*.rake
    - db/migrate/*.rb
    - bin/*

#################### Style ###########################

Style/CommentAnnotation:
  Keywords:
    - TODO-SNAPCON
    - TODO
    - OPTIMIZE
    - HACK
    - REVIEW

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/EndOfLine:
  EnforcedStyle: lf

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - features/step_definitions/*

##################### Metrics ##################################

##################### Rails ##################################

##################### RSpec ##################################

RSpec/DescribeClass:
  Exclude:
    - "spec/views/**/*"
    - "spec/ability/*"
